### ISSUE TITLE
Issue when using 'address' type

### ISSUE THREAD

**Issue by charliemitchell** [dmuneras/ember-place-autocomplete#44]
Hello, There seems to be an issue when using 'address' as the type... maybe other types too, but I've experienced the issue only when using the `address` type. 

Essentially, the call to `getPlace` returns the wrong place sometimes. 
For example. If you search for 324 2nd St. Camino, CA the result comes back as something entirely different. The suggestion is correct, but the call to `getPlace` is off. I suspect that this happens when you enter an address that either google does not know exists, or an address that doesn't exist. I have my suspicions, but I've yet to confirm. I provided a code pen for you to review, and illustrated the response from getPlace. I'm not sure what the right call is here, but It may be nice to compare the place to getPlace() and if they are in a different city etc... handle that. If it is an invalid address, and someone has the time to confirm that this is indeed what's happening, then maybe fire a callback that we can use so that we can handle it how we see fit.

[CodePen Example](https://codepen.io/charliemitchell/pen/JWKdBw)

**Comment by dmuneras** [comment]
Hi @charliemitchell,

Thanks for the report and for taking the time to do a research about it.  I am going to take a look this weekend. 

Regards,
Daniel.

**Comment by dmuneras** [comment]
Hey @charliemitchell,

Sorry for the super super late response. I read it and I was sure I answered it, but not. 

If you don't select the suggestion, the name that is going to be sent to google in order to get the full information is the one on the text field, not the one in the suggestion, you have to select the suggestion so the field changes its value and you get the full info. 

I was thinking about selecting the first prediction and updating the field with its value, but, I didn't do it because some people needs the name to store 'custom places', like: 'REMOTE', 'IN HOUSE'.

I just update the addon to fix some small details and upgrade libraries, maybe what we can do is add an option like `onlyPlacesInGoogle` and default the value to the first prediction option when the value in the field doesn't return information from google. 

Let me know if:
* I correctly understood your problem 
* You have better options to fix it
* If you want to fix it yourself and open a PR.

Best regards,
Daniel.
