### ISSUE TITLE
Support for session token

### ISSUE THREAD

**Issue by Kernes** [dmuneras/ember-place-autocomplete#74]
Hello,

With the new Places API Usage and Billing we can now specify a `session token` with every Autocomplete request.
Does your addon provide a way to do that or is there any plan to make it possible?

Thanks!

**Comment by dmuneras** [comment]
Hey @Kernes!

Being honest I haven't taken a look at it yet. Will do this week and reply to you here.

**Comment by simonc** [comment]
Hey @dmuneras,

Did you have any time to take a look? I’d love to do a PR on this but sadly JS is not really my domain of expertise :sweat_smile:

I think a lot of people would found it cool to be able to reduce their costs now that Google changed its pricing 😊

Thanks! :heart:

**Comment by dmuneras** [comment]
@simonc @Kernes  Sorry that this is taking long, I have been having very interesting weeks at work which have preventing me from looking at this issue.. I will do my best to address this weekend.

**Comment by dmuneras** [comment]
@simonc  @Kernes finally I was able to take a look at this. Looking at the documentation, it looks like the session token is something that you can set when using `AutocompleteService` but not when using `Autocomplete`. I was reading people comments I am some people says that while using `Autocomplete` the session token is added automatically, but I am not seeing it in the requests. 

It would be much appreciated if you can confirm that you are being billed for every request and the session token is not being added. 

As final comment. I am planning to create a service in this addon to allow people to use `AutocompleteService`, once I implement that I can give you options to generate a session token and use it in your requests. Let me check what could I do to improve this, because it feel important, even for the company I work with. 

Best regards and sorry for the delay to answer,
Daniel.

**Comment by simonc** [comment]
Hi @dmuneras I've looking at the requests sent to AutocompleteService and I am not sure of all the pieces involved.

The called URLs look like this
```
https://maps.googleapis.com/maps/api/place/js/AutocompletionService.GetPredictions?1s1234&4sen-US&15e3&20sB57BD9FA-A881-4FB6-90DF-5762EABAF3D1u36f063k2v2q&21m1&2e1&callback=_xdc_._75qgmo&key=<API KEY>&token=117009
```
And the inspector shows the following params for this request
```
15e3:
1s1234:
20sB57BD9FA-A881-4FB6-90DF-5762EABAF3D1u36f063k2v2q:
21m1:
2e1: 
4sen-US:
callback: _xdc_._75qgmo
key: <API KEY>
token: 117009
```

The `token` here seem to change according to the typed search.

The second param though, `20sB57BD9FA-A881-4FB6-90DF-5762EABAF3D1u36f063k2v2q` seems stable from request to request, athough it changes from one browser to the other.

TBH I have no idea what it stands for. Since the documentation clearly shows a param explicitely named `sessionToken` I don't think it's the same thing.

Regarding our billing I have no idea how to be sure the requests are grouped by session or not. Do you know where this information can be gathered?

Thanks!

**Comment by dmuneras** [comment]
Hey @simonc  and @Kernes!

I got some time to work on improving the addon and I added support to use the Google Places API as a service, which allow the usage of the `sessionToken`. You can read how you can use it here: 

https://dmuneras.github.io/ember-place-autocomplete/usage/service

It is not released, but you can point to the master branch to test it if you want to. I still have to do some other updates before releasing that work, but I don't think it is going to take longer than 1 or 2 weeks. 

Hope this is helpful,
Daniel.

**Comment by simonc** [comment]
Hi @dmuneras,

@Kernes and I left the company that needed this. We'll keep working on Ember apps on the side and we may need this  soon. We'll definitely test the master brqnch when the time comes.

Thanks a lot!

**Comment by dmuneras** [comment]
I am closing this issue because it seems to be resolved using the new service. 😄
