### ISSUE TITLE
Test Mocks are not usable by consumers

### ISSUE THREAD

**Issue by josemarluedke** [dmuneras/ember-place-autocomplete#93]
The test mock setup is not accessible by consumers. 

Currently, these test helpers live inside of the `tests` folders and they are not shipped to NPM. 

Even if they were shipped to NPM, that's not the right place to have test helpers to be consumed by others. 

If an addon wants to ship a test helper, they should have them at `addon-test-support`. 

For more references, check other addons. One example is [ember-power-select](https://github.com/cibernox/ember-power-select/tree/master/addon-test-support).

**Comment by dmuneras** [comment]
Hi @josemarluedke!

Thanks for the reference. I will have a look at it and do the required changes this week or the week after. Being honest, there is a big room of improvement to improve testing support, so, I will be glad to jump into it.

Best regards,
Daniel.

**Comment by dmuneras** [comment]
Hi @josemarluedke,

I am sorry this took longer than expected. I just released a version with the test helpers available and some other fixes. I hope it is usable enough outside of the addon scope, since I created the helpers only to write tests for the addon. I might need to review how to make them more general and usable. 

I am going to close the issue, but feel free to open it again if the resolution is not good enough.

Best regards,
Daniel.
